name: Diffusion-Models-ENSO
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - xarray
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - cartopy
  - libnetcdf
  - gdal
  - pip:
      - poetry
